# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-03 17:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0005_lobbyusermap'),
    ]

    operations = [
        migrations.AddField(
            model_name='lobby',
            name='started',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lobbyusermap',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
    ]
